application: sample
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: tmp/index.html
  upload: tmp/index.html

- url: /(.*)
  static_files: tmp/\1
  upload: tmp/(.*)

- url: /css
  static_dir: tmp/css
  
- url: /(.*\.(gif|png|jpg))
  static_files: tmp/images
  upload: tmp/images/(.*\.(gif|png|jpg))
  
- url: /js
  static_dir: tmp/js

- url: /main/.*
  script: main.py
  secure: always